
    - name: Clone the frontend repository
      git:
        repo: 'https://{{ github_token }}@github.com/NazarPry/FrontArtifacts.git'  
        dest: /home/vagrant/frontend  

   
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Remove default Nginx site if exists
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Collect backend IPs
      set_fact:
        backend_ips: "{{ groups['backend'] }}"

    - name: Configure Nginx to serve frontend
      template:
        src: nginx-frontend.j2  
        dest: /etc/nginx/sites-available/frontend

    
    - name: Enable frontend site in Nginx
      file:
        src: /etc/nginx/sites-available/frontend
        dest: /etc/nginx/sites-enabled/frontend
        state: link
      
    - name: Move build files to Nginx directory
      copy:
        src: /home/vagrant/frontend/
        dest: /var/www/frontend/
        remote_src: yes
    
    - name: Restard Nginx
      service:
        name: nginx
        state: restarted
