    - name: Ensure PostgreSQL is installed
      apt:
        name: postgresql
        state: present
        update_cache: yes

    - name: Ensure python3-psycopg2 is installed
      apt:
        name: python3-psycopg2
        state: present
        update_cache: yes
   
    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes
    
    - name: Create a new PostgreSQL database
      postgresql_db:
        name: "{{ db_name }}"
        state: present
      become_user: postgres
      
        
    - name: Create a new PostgreSQL user
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        state: present
      become_user: postgres

    - name: Grant all privileges on the database to the user
      postgresql_privs:
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        privs: ALL
        type: database
        state: present
      become_user: postgres

    - name: Grant all privileges on the public schema to the user
      postgresql_privs:
        db: "{{ db_name }}"
        role: "{{ db_user }}"
        objs: public
        privs: ALL
        type: schema
      become_user: postgres

    - name: Set PostgreSQL options
      community.postgresql.postgresql_set:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      become: true
      become_user: postgres
      loop: "{{ db_options }}"

    - name: Add entries to pg_hba
      community.postgresql.postgresql_pg_hba:
        dest: "/etc/postgresql/{{ db_version }}/main/pg_hba.conf"
        address: "{{ access_network }}"
        contype: host
        databases: all
        method: md5
        users: "{{ db_user }}"
      become: true
      become_user: postgres


    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted

